apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app traefik-internal
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 39.0.9
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      annotations:
        io.cilium/lb-ipam-ips: "${IPAM_IP_TRAEFIK_INTERNAL}"
      spec:
        externalTrafficPolicy: Cluster
    env:
      - name: TZ
        value: "${TIMEZONE}"
    logs:
      access:
        enabled: true
    ingressClass:
      isDefaultClass: false
      name: traefik-internal
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.${SECRET_DOMAIN}`)
        entryPoints: ["websecure"]
        middlewares:
          - name: network-chain-no-auth-restrict-networks@kubernetescrd
        services: [{"kind":"TraefikService","name":"api@internal"}]
        tls:
          secretName: "${SECRET_DOMAIN/./-}-production-tls"
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        http:
          tls:
            options: default
        transport:
          respondingTimeouts:
            readTimeout: "0"
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
    metrics:
      prometheus:
        entryPoint: metrics
        service:
          enabled: true
    providers:
      kubernetesCRD:
        ingressClass: traefik-internal
        allowCrossNamespace: true
      kubernetesIngress:
        ingressClass: traefik-internal
        allowExternalNameServices: true
      kubernetesGateway:
        enabled: true
        labelSelector: "traefik-instance=internal"
    gateway:
      enabled: false
    gatewayClass:
      name: traefik-internal
      labels:
        traefik-instance: internal
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: traefik-internal
            app.kubernetes.io/component: controller
    resources:
      requests:
        cpu: 23m
        memory: 814M
      limits:
        memory: 1G
