---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      sabnzbd:
        annotations:
          secret.reloader.stakater.com/reload: sabnzbd-pia

        containers:
          pia-tun:
            image:
              repository: ghcr.io/x0lie/pia-tun
              tag: develop@sha256:17a25914c103fde27123a8cca5a8df048db4dd0f9cd6f49de5459d98404af16e
            env:
              TZ: ${TIMEZONE}
              LOG_LEVEL: "debug"
              BOOTSTRAP_DNS: "10.96.0.10"
              DNS: "tls://one.one.one.one, dns9.quad9.net"
              LOCAL_NETWORKS: "10.69.0.0/16, 10.96.0.10/32"
              SOCKS5_ENABLED: "true"
            envFrom:
              - secretRef:
                  name: sabnzbd-pia
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 50M
            securityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_ADMIN
                drop:
                  - ALL
          sabnzbd:
            dependsOn: pia-tun
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.5@sha256:f5570c0a370596ab656db6d3baa830b90a6fd9952b71ae805d022a2dcb3db12f
            env:
              TZ: ${TIMEZONE}
              PUID: "1001"
              PGID: "1001"
              UMASK: "022"
              SABNZBD__HOST_WHITELIST_ENTRIES: sabnzbd.media.svc.cluster.local, sabnzbd.${SECRET_DOMAIN}
            resources:
              requests:
                cpu: 10m
                memory: 1641M
              limits:
                memory: 3561M
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
    service:
      sabnzbd:
        controller: *app
        ports:
          http:
            port: 8080
          socks5:
            port: 1080
          metrics:
            port: 9090
    persistence:
      config:
        enabled: true
        storageClass: nfs-csi          # Dynamic PVC in /kubernetes/appdata
        accessMode: ReadWriteMany
        size: 2Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc   # Uses static PVC for /kubernetes/media
      tmp:
        type: emptyDir
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "Always"
