---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: vaultwarden
        containers:
          main:
            image:
              repository: vaultwarden/server
              tag: 1.37.2@sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912
            env:
              DATA_FOLDER: data
              ICON_CACHE_FOLDER: data/icon_cache
              ATTACHMENTS_FOLDER: data/attachments
              DOMAIN: "https://vaultwarden.${SECRET_DOMAIN}"
              DISABLE_ICON_DOWNLOAD: "true"
              TZ: "${TIMEZONE}"
              SIGNUPS_ALLOWED: "false"
              WEBSOCKET_ENABLED: "true"
              WEBSOCKET_ADDRESS: 0.0.0.0
              WEBSOCKET_PORT: 3012
              # SMTP_HOST: smtp-relay.default.svc.cluster.local.
              # SMTP_FROM: vaultwarden@${SECRET_DOMAIN}
              # SMTP_FROM_NAME: vaultwarden
              # SMTP_PORT: 2525
              # SMTP_SECURITY: "off"
            envFrom:
              - secretRef:
                  name: vaultwarden
            resources:
              requests:
                cpu: 15m
                memory: 105M
              limits:
                memory: 655M
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 80
    persistence:
      config:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 2Gi
        globalMounts:
          - path: /data

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "Always"
