# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      qbittorrent:
        annotations:
          secret.reloader.stakater.com/reload: qbittorrent-pia

        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          pia-tun:
            image:
              repository: ghcr.io/x0lie/pia-tun
              tag: develop@sha256:17a25914c103fde27123a8cca5a8df048db4dd0f9cd6f49de5459d98404af16e
            env:
              TZ: ${TIMEZONE}
              LOG_LEVEL: "debug"
              BOOTSTRAP_DNS: "10.96.0.10"
              DNS: "tls://one.one.one.one, dns9.quad9.net"
              LOCAL_NETWORKS: "10.69.0.0/16"
              PS_CLIENT: "qbittorrent"
            envFrom:
              - secretRef:
                  name: qbittorrent-pia
            resources:
              requests:
                cpu: 10m
                memory: 53M
              limits:
                memory: 91M
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_ADMIN
                drop:
                  - ALL

          qbittorrent:
            dependsOn: [pia-tun]
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.4
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 22m
                memory: 2280M
              limits:
                memory: 6413M
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080
          metrics:
            port: 9090

    serviceMonitor:
      app:
        serviceName: qbittorrent
        endpoints:
          - port: metrics

    persistence:
      config:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 2Gi
        advancedMounts:
          qbittorrent:
            qbittorrent:
              - path: /config
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /media
      downloads:
        enabled: true
        existingClaim: nfs-torrents-pvc
        globalMounts:
          - path: /downloads
