apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app traefik-external
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 39.0.9
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    deployment:
      replicas: 2
    service:
      annotations:
        io.cilium/lb-ipam-ips: "${IPAM_IP_TRAEFIK_EXTERNAL}"
      spec:
        externalTrafficPolicy: Cluster
    env:
      - name: TZ
        value: "${TIMEZONE}"
    logs:
      access:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`ext-traefik.${SECRET_DOMAIN}`)
        entryPoints: ["websecure"]
        middlewares:
          - name: network-chain-no-auth-restrict-networks@kubernetescrd
        services: [{"kind":"TraefikService","name":"api@internal"}]
        tls:
          secretName: "${SECRET_DOMAIN/./-}-production-tls"
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        http:
          tls:
            options: default
        transport:
          respondingTimeouts:
            readTimeout: "0"
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 108.162.192.0/18
            - 131.0.72.0/22
            - 141.101.64.0/18
            - 162.158.0.0/15
            - 172.64.0.0/13
            - 173.245.48.0/20
            - 188.114.96.0/20
            - 190.93.240.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 2400:cb00::/32
            - 2606:4700::/32
            - 2803:f800::/32
            - 2405:b500::/32
            - 2405:8100::/32
            - 2a06:98c0::/29
            - 2c0f:f248::/32
    metrics:
      prometheus:
        entryPoint: metrics
        service:
          enabled: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
        labelSelector: "traefik-instance=external"
    gateway:
      enabled: false
    gatewayClass:
      name: traefik-external
      labels:
        traefik-instance: external
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: traefik-external
            app.kubernetes.io/component: controller
    resources:
      requests:
        cpu: 23m
        memory: 549M
      limits:
        memory: 1G
