# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: nvidia-device-plugin
      namespace: kube-system
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        containers:
          main:
            image:
              repository: linuxserver/plex
              tag: 1.43.3@sha256:de95bb12db3ed4e34ad5983113b8af967cfd77786e15669c0703c22133e10107
            env:
              TZ: ${TIMEZONE}
              PUID: "1001"
              PGID: "1001"
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
            resources:
              requests:
                cpu: 49m
                memory: 2048M
                nvidia.com/gpu: 1
              limits:
                memory: 4046M
                nvidia.com/gpu: 1

    service:
      main:
        controller: main
        ports:
          http:
            port: 32400

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: plex-config
      media:
        enabled: true
        existingClaim: nfs-media-pvc
      transcode:
        enabled: true
        type: emptyDir

    defaultPodOptions:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.feature.node.kubernetes.io/gpu: "true"
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
